### PR TITLE
After reviews made in #4, here is a refined PR.

### PR DESCRIPTION
**Pull request by doronbehar**

### CODE REVIEW

**Comment by doronbehar** [comment]
OK, few things I have in mind:

1. First of all, `luacheck` gave warnings for the main `pulseaudio_dbus.lua` for long comment lines with `ldoc` links to dbus documentations. I disabled them with `max_comment_line_length = false` in `.luacheckrc`.
2. Besides that, I ran `luacheck` on the test file and besides the issue I solved of spaces mixed with tabs, most of the warnings are related to the fact that `busted` is running the function `b.before_each` concatenated before each `b.it` test. To suppress these warnings, I added `allow_defined = true` option to the command.
3. In addition, most of the other warnings `luacheck` gives for `tests/pulseaudio_dbus_spec.lua` were produced because of the undefined fields `are.equal` `are.same` and `is_equal` etc. In order to suppress these warnings I added `std = "_G+busted"` to `.luacheckrc` (according to [`luacheck`'s documentation on "Custom sets of globals"](http://luacheck.readthedocs.io/en/stable/config.html#custom-sets-of-globals).
4. After that, I was left with only 2 warnings regarding lines [201](https://github.com/doronbehar/lua-pulseaudio_dbus/blob/multiple-sinks-rerefined/tests/pulseaudio_dbus_spec.lua#L201) and [228](https://github.com/doronbehar/lua-pulseaudio_dbus/blob/multiple-sinks-rerefined/tests/pulseaudio_dbus_spec.lua#L228) (*note the branch* [`multiple-sinks-rerefined`](https://github.com/doronbehar/lua-pulseaudio_dbus/tree/multiple-sinks-rerefined)) implying the lines are too long. Could we tolerate these only 2 warnings?
5. Besides that, the idea I held in mind when updating all the tests to manipulate them so they will run for all sinks was to practice the new multiple sinks feature. Are you sure It won't hold any value to test all the sinks?
6. Should I push the following `.luacheckrc` and perhaps even create a separate PR?
```lua
allow_defined = true
max_comment_line_length = false
std = "_G+busted"

-- vim:ft=lua
```

**Comment by doronbehar** [comment]
I noticed you haven't added the `allow_defined = true;` flag for `files["tests"]` object in [`.luacheckrc`](https://github.com/stefano-m/lua-pulseaudio_dbus/blob/master/.luacheckrc#L2). I'm using the latest version of `luacheck` and I still get many errors for undefined variables as I explained in my previous comment.
Besides that my new PR is ready.

**Comment by stefano-m** [comment]
You can easily avoid those warning by defining `local` variables within the `describe` function. I am now working on merging #6 but, please, next time give more meaningful names to your PRs and branches.

Thanks!

**Comment by stefano-m** [comment]
Closing. Superseded by #6

**Pull request closed without merging**
