### PR TITLE
Use sink as an object after all. (fix for #7)

### PR DESCRIPTION
**Pull request by doronbehar**
Use `sink[1]` for the old tests.
Add `allow_defined = true;` to `.luacheckrc` for files in `tests`.
EDIT: Merge branch master.

### CODE REVIEW

**Comment by stefano-m** [comment]
Propsed fix for #7

**Comment by doronbehar** [comment]
Seems acceptable and rather creative to me :)
If I understood you correct, the diff you proposed above should be merged to branch master while ignoring this PR right?
Note that currently I can't test the proposed version because I'm not home until the weekend and I don't have multiple sinks here but satisfyingly it doesn't give any errors.

**Comment by stefano-m** [comment]
@doronbehar the patch is completely untested, but it conforms to the API. You get an address from the `core` object and use that address to get an actual `Sink` proxy object. The patch is against the current master branch, but I'll leave it to you to verify that it works. No hurry though!

And yes, I'd rather merge something like the patch above than a more invasive change to the full test suite.

Thanks.

**Comment by doronbehar** [comment]
You will get my final approval on Thursday.

**Pull request closed without merging**
